{
 "title": "Gryphon dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Cumulative of last period", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backend Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"backend\"} | json level=\"level\" | drop filename, job, service_name [7d])"
    }
   ]
  },
  {
   "title": "Most logged actions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by(action) (count_over_time({job=\"backend\"} | json action=\"action\", level=\"level\" | keep action, level [7d])))"
    }
   ]
  },
  { "title": "Live", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Last logs",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"backend\"} | json level=\"level\", action=\"action\", message=\"message\" | keep level, action, message"
    }
   ]
  }
 ]
}